version: "3.9"

services:
  nextjs:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      ANALYSIS_SERVICE_URL: http://host.docker.internal:8000
    command: npm run dev
    ports:
      - "3007:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./dataset:/app/dataset
    extra_hosts:
      - "host.docker.internal:host-gateway"
